services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assista-main
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
    restart: unless-stopped

networks:
  assita-builder_default:
    external: true
  assista-wiki_assista-network:
    external: true
